export const featuredProducts = [
  {
    id: "1",
    name: "VisionAI",
    slug: "visionai",
    tagline: "See beyond the pixels.",
    description: "AI-powered image recognition for smart apps",
    websiteUrl: "https://visionai.example.com",
    tags: ["AI", "Vision", "Tools"],
    createdAt: new Date("2025-01-11"),
    approvedAt: new Date("2025-01-12"),
    status: "approved",
    submittedBy: "alice@visionai.com",
    voteCount: 234,
    isFeatured: true,
  },
  {
    id: "2",
    name: "CodeFlow",
    slug: "codeflow",
    tagline: "Collaborate. Ship. Win.",
    description: "Collaborative coding platform for teams",
    websiteUrl: "https://codeflow.example.com",
    tags: ["Collaboration", "Coding", "Teams"],
    createdAt: new Date("2025-01-14"),
    approvedAt: new Date("2025-01-16"),
    status: "approved",
    submittedBy: "bob@codeflow.dev",
    voteCount: 0,
    isFeatured: false,
  },
  {
    id: "3",
    name: "TaskWave",
    slug: "taskwave",
    tagline: "Ride the productivity wave.",
    description: "Intuitive task management for productivity",
    websiteUrl: "https://taskwave.example.com",
    tags: ["Productivity", "Tasks", "Workflow"],
    createdAt: new Date("2025-01-18"),
    approvedAt: new Date("2025-01-19"),
    status: "approved",
    submittedBy: "carol@taskwave.io",
    voteCount: 0,
    isFeatured: false,
  },
  {
    id: "4",
    name: "SocialSpark",
    slug: "socialspark",
    tagline: "Ignite your community.",
    description: "Build instant communities around your projects",
    websiteUrl: "https://socialspark.example.com",
    tags: ["Community", "Social", "Engagement"],
    createdAt: new Date("2025-01-21"),
    approvedAt: new Date("2025-01-22"),
    status: "approved",
    submittedBy: "dave@socialspark.co",
    voteCount: 0,
    isFeatured: true,
  },
  {
    id: "5",
    name: "DataDrift",
    slug: "datadrift",
    tagline: "Analytics that move with you.",
    description: "Real-time analytics for modern web applications",
    websiteUrl: "https://datadrift.example.com",
    tags: ["Analytics", "Data", "Real-Time"],
    createdAt: new Date("2025-01-07"),
    approvedAt: new Date("2025-01-10"),
    status: "approved",
    submittedBy: "ella@datadrift.com",
    voteCount: 123,
    isFeatured: false,
  },
  {
    id: "6",
    name: "PixelPush",
    slug: "pixelpush",
    tagline: "Web design made simple.",
    description: "Drag-and-drop website builder for any skill level",
    websiteUrl: "https://pixelpush.example.com",
    tags: ["Design", "Builder", "Website"],
    createdAt: new Date("2025-01-24"),
    approvedAt: new Date("2025-01-26"),
    status: "approved",
    submittedBy: "frank@pixelpush.dev",
    voteCount: 45,
    isFeatured: false,
  },
  {
    id: "7",
    name: "SecureBase",
    slug: "securebase",
    tagline: "Lock down your users.",
    description: "Next-gen authentication for secure user experience",
    websiteUrl: "https://securebase.example.com",
    tags: ["Security", "Authentication", "User"],
    createdAt: new Date("2025-01-02"),
    approvedAt: new Date("2025-01-05"),
    status: "approved",
    submittedBy: "grace@securebase.io",
    voteCount: 87,
    isFeatured: true,
  },
  {
    id: "8",
    name: "CloudFuse",
    slug: "cloudfuse",
    tagline: "Connect with the cloud, instantly.",
    description: "Easy cloud integrations for SaaS products",
    websiteUrl: "https://cloudfuse.example.com",
    tags: ["Cloud", "Integration", "SaaS"],
    createdAt: new Date("2025-01-27"),
    approvedAt: new Date("2025-01-28"),
    status: "approved",
    submittedBy: "helen@cloudfuse.cloud",
    voteCount: 31,
    isFeatured: false,
  },
  {
    id: "9",
    name: "MarketPulse",
    slug: "marketpulse",
    tagline: "Feel the rhythm of the market.",
    description: "Track trends with intelligent market analytics",
    websiteUrl: "https://marketpulse.example.com",
    tags: ["Market", "Analytics", "Trends"],
    createdAt: new Date("2025-01-13"),
    approvedAt: new Date("2025-01-15"),
    status: "approved",
    submittedBy: "ivan@marketpulse.net",
    voteCount: 256,
    isFeatured: true,
  },
];
